### ISSUE TITLE
总结 Ant Design 设计规范，日文版作为公司设计规范参考

### ISSUE THREAD

**Issue by ThaddeusJiang** [ThaddeusJiang/Weekly#42]
![img_8541](https://user-images.githubusercontent.com/17308201/37865343-ad6f6820-2fbe-11e8-978c-fbf2ed7b8b40.JPG)

![img_8542](https://user-images.githubusercontent.com/17308201/37865352-bd18215e-2fbe-11e8-99e3-e450ee3c303a.JPG)

**Comment by afc163** [comment]
来给 Ant Design 提供一个日文版如何？

**Comment by ThaddeusJiang** [comment]
@afc163 可以尝试，哈哈。
公司新项目使用 Ant Design 作为前端框架，超级好用，文档还详细。👍
